name: Build & Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      # Snapcraft needed for building Linux AppImage
      - name: Install Snapcraft
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo snap install snapcraft --classic

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm install
          pnpm postinstall

      - name: Build & Publish release
        run: |
          pnpm build
          pnpm exec electron-builder --publish=always
        env:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #################################################
          ## MacOS specific
          # used for signing application :
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # used for signing package installer:
          # CSC_INSTALLER_LINK: ${{ secrets.CSC_INSTALLER_LINK }}
          # CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.CSC_INSTALLER_KEY_PASSWORD }}
          # used for notarization : https://www.npmjs.com/package/electron-builder-notarize
          APPLE_ID: ${{ secrets.APPLE_ID  }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD  }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          #################################################
          ## Linux/Snapcraft specific
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}


          #################################################
